queries: ["park bench"]
# semantic_target: "mannequin"

hoverMode: False
numTraj: all

visualize: True

visualize: True

# Set the default parameters for the RRT algorithm
algorithm: 'RRT*'
N: 1000
dimension: '2'
prevent_edge_overlap: 'y'
exact_step: 'n'
bounded_step: 'y'

#Set the parameters for the semantic objective
minbound: [-1, -1, -2.5]
maxbound: [0, 0, 0]
# minbound: [-4.5, -2.0, -2.0]
# maxbound: [4.5, 2.0, 0.0]
# minpbound: [2.0, 2.0, 2.0]
# maxpbound: [2.0, 2.0, 2.0]

r1: 1.5
r2: 0.5

altitude: -2.0

# Visualization parameters
gif: False
