queries: ["ladder"]
# semantic_target: "mannequin"

hoverMode: False
numTraj: all

visualize: True

visualize: True

# Set the default parameters for the RRT algorithm
algorithm: 'RRT*'
N: 1000
dimension: '2'
prevent_edge_overlap: 'y'
exact_step: 'n'
bounded_step: 'y'
obj_exclusion_radius: 0.5
obstacle_exclusion_radius: 0.5

# Set the default parameters for semantic objective
r1: 0.2 # distance to the pointcloud centroid
r2: 0.2 # collision check distance from point at end of r1 vector

# BBox parameters
# minbound: [None, None, 0.0]
# maxbound: [None, None, 2.2]
minbound: [None, -4, -2]
maxbound: [None, 4, 0]
# minpbound: [2.0, 2.0, 2.0]
# maxpbound: [2.0, 2.0, 2.0]
