queries: ["mannequin", "textbook on stool", "water barrel"]
# queries: ["mannequin", "water barrel"]
# queries: ["textbook on stool"]
# queries: ["mannequin"]
# semantic_target: "mannequin"

radii:
  - [ 1.0,  0.4]   # for "mannequin"
  - [ 2.0,  0.4]   # for "textbook on stool"
  - [ 1.8,  0.4]   # for "water barrel"

altitudes:
  - -1.0            # flight height for "mannequin"
  - -0.9            # flight height for "ladder”
  - -1.0            # flight height for "water barrel"

similarities:
  - [ 0.90, 0.025 ]  # threshold, filter radius
  - [ 0.90, 0.025 ]
  - [ 0.90, 0.025 ]

hoverMode: False
numTraj: all

visualize: False

# Set the default parameters for the RRT algorithm
algorithm: 'RRT*'
N: 80
dimension: '2'
prevent_edge_overlap: 'y'
exact_step: 'n'
bounded_step: 'y'
step_size: 1.0

#Set the parameters for the semantic objective
minbound: [-3, -6, -2]
maxbound: [3, 6, 0]
# minbound: [-4.5, -2.0, -2.0]
# maxbound: [4.5, 2.0, 0.0]
# minpbound: [2.0, 2.0, 2.0]
# maxpbound: [2.0, 2.0, 2.0]

# r1: 1.5
# r2: 0.5

# altitude: -1.1

gif: False