queries: ["man sitting", "bicycle", "desk chair"]
# queries: ["guy in jacket", "computer"]
# queries: ["man sitting"]
# queries: ["basketball"]
# queries: ["bicycle"]
# queries: ["desk chair"]
# semantic_target: "mannequin"

radii:
  - [ 1.5,  0.45]   # for "microwave"
  - [ 1.5,  0.45]   # for "computer"
  - [ 1.0,  0.45]   # for "armchair"

altitudes:
  - -1.1            # flight height for “microwave”
  - -0.9            # flight height for "ladder”
  - -1.0            # flight height for "armchair"

similarities:
  - [ 0.90, 0.025 ]  # threshold, filter radius
  - [ 0.90, 0.025 ]
  - [ 0.90, 0.025 ]

nbranches:
  - 120
  - 120
  - 120

hoverMode: False
numTraj: all

visualize: False

# Set the default parameters for the RRT algorithm
algorithm: 'RRT*'
N: 1000
dimension: '2'
prevent_edge_overlap: 'y'
exact_step: 'n'
bounded_step: 'y'
step_size: 1.5
collision_check_resolution: 0.25

#Set the parameters for the semantic objective
minbound: [-3, -4, -2]
maxbound: [2, 3.8, 0]


# r1: 1.5
# r2: 0.2
# altitude: -1.1

gif: False
